version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/app
    ports:
      - "5000:80"
    environment:
      - FLASK_APP=flaskr/flask_app.py
      - FLASK_RUN_PORT=80
      - FLASK_DEBUG=1
      - PRIMELY_ROOT=/opt/app
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"